name: Test SSH Connection

on:
  workflow_dispatch:
    inputs:
      test_type:
        description: 'Тип теста'
        required: false
        default: 'basic'

jobs:
  test-ssh:
    runs-on: ubuntu-latest
    
    steps:
    - name: Test SSH connection
      run: |
        echo "🔑 Проверяем SSH ключ..."
        
        # Проверяем, есть ли ключ в секретах
        if [ -z "${{ secrets.SERVER_SSH_KEY }}" ]; then
          echo "❌ SERVER_SSH_KEY секрет не настроен!"
          echo "📋 Инструкция:"
          echo "1. Зайдите на сервер через панель хостинга"
          echo "2. Выполните: ssh-keygen -t rsa -b 4096 -f ~/.ssh/github_key"
          echo "3. Выполните: cat ~/.ssh/github_key.pub >> ~/.ssh/authorized_keys"
          echo "4. Скопируйте: cat ~/.ssh/github_key"
          echo "5. Добавьте в GitHub Secrets как SERVER_SSH_KEY"
          exit 1
        fi
        
        # Настраиваем SSH
        mkdir -p ~/.ssh
        echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H rualtech.ru >> ~/.ssh/known_hosts
        
        echo "🧪 Тестируем SSH подключение..."
        
        # Простой тест подключения
        if ssh -o ConnectTimeout=10 root@rualtech.ru "echo 'SSH работает!'; hostname; whoami"; then
          echo "✅ SSH подключение успешно!"
        else
          echo "❌ SSH подключение не удалось"
          echo "🔍 Возможные причины:"
          echo "- Неправильный SSH ключ в секретах"
          echo "- Ключ не добавлен в ~/.ssh/authorized_keys на сервере"
          echo "- Неправильные права доступа к файлам SSH"
          exit 1
        fi
